version: 2.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello job

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello <<CIRCLE_BUILD_NUM>> $env_name

workflows:
  first-workflow:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello